"""makes purchase date unique

Revision ID: 24bd8b96b95a
Revises: 8018caceb476
Create Date: 2026-03-04 12:42:01.924922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24bd8b96b95a'
down_revision: Union[str, Sequence[str], None] = '8018caceb476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_purchase_purchase_date'), 'purchase', ['purchase_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_purchase_date'), table_name='purchase')
    # ### end Alembic commands ###
