services:

  devops-toolbox:
    build:
      context: .
      dockerfile: ../.devcontainer/devops-toolbox/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity

  angular-frontend:
    build:
      context: ../angular-frontend
      dockerfile: ../.devcontainer/angular-frontend/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    ports:
      - "4200:4200"
    depends_on:
      fastapi-backend:
        condition: service_started

  fastapi-backend:
    build:
      context: ../fastapi-backend
      dockerfile: ../.devcontainer/fastapi-backend/Dockerfile
    volumes:
      - ..:/workspace:cached
    environment:
      RUN_CONTEXT: devcontainer
    command: sleep infinity
    ports:
      - "8000:8000"
    depends_on:
      postgres-database:
        condition: service_healthy

  postgres-database:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: purchases
    volumes:
      - ../postgres-database/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5432 -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
